version: '3'

services:

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app_network
    restart: always

  server:
    build: ./server
    container_name: server
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_JWT_SECRET=${SERVER_JWT_SECRET}
      - WEBSITE_ADDRESS=${WEBSITE_ADDRESS}
      - WEBSITE_PORT=${WEBSITE_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app_network
    restart: always

  website:
    build: ./website
    container_name: website
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - WEBSITE_PORT=${WEBSITE_PORT}
      - WEBSITE_JWT_SECRET=${WEBSITE_JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    ports:
      - "${WEBSITE_PORT}:${WEBSITE_PORT}"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
